export type TeamspeakEventType =
	| 'error'
	| 'ready'
	| 'close'
	| 'flooding'
	| 'debug'
	| 'clientconnect'
	| 'clientdisconnect'
	| 'tokenused'
	| 'textmessage'
	| 'clientmoved'
	| 'serveredit'
	| 'channeledit'
	| 'channelcreate'
	| 'channelmoved'
	| 'channeldelete';
